### ISSUE TITLE
fix join-us page/redirect

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#1015]
join us page is redirecting to main lbry.com. We show it on the team page.
https://github.com/lbryio/lbry.com/blob/22172654c24a50dc39f19b995153a6fb874bbfbf/data/redirect/temporary.yaml

Did it need some work before enabling?

**Comment by kauffj** [comment]
Fixed, but there are styling issues https://github.com/lbryio/lbry.com/issues/1020
