### ISSUE TITLE
fix styling on /join-us

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#1020]
Issues:

- [ ] The "Hiring Process" section (bullets in table, spacing, table in list)
- [ ] Lack of hero image (maybe take the image and put it in the hero?)

**Comment by NetOperatorWibby** [comment]
I thought this page was retired. Also, the image on the page is inaccurate...should it really be the hero image?

**Comment by kauffj** [comment]
It's not retired, it's just not being emphasized in nav
