### ISSUE TITLE
Provide button to open app after verifying email

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#1033]
For mobile, desktop, and web.

**Comment by tzarebczan** [comment]
We need to check what triggered the verification...if it was something like YouTube sync, we don't want to show an open app button.

**Comment by tzarebczan** [comment]
The requested from platform is now included in the verification response: https://github.com/lbryio/internal-apis/pull/973

This should work on Desktop, but Mobile still needs a tweak: https://github.com/lbryio/lbry-android/issues/665 - so we can enable now for desktop, and add mobile later. 

The button should say something like "Go back to the App" if the platform response matches the current platform they are on. The button would link to lbry://?account (for Desktop at least, mobile most likely too, but TBD in the linked issue).

**Comment by kauffj** [comment]
I think we decided this isn't that important

**Comment by tzarebczan** [comment]
Closing this for now, it would be on the lbry.tv side if we wanted to add it.
