### ISSUE TITLE
address facebook / other scripts when visiting

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#1058]
see https://www.reddit.com/r/lbry/comments/c4aire/why_does_lbrycom_embed_facebook_scripts/

**Comment by kauffj** [comment]
I'm not sure what to do about this. As long as we want to run campaigns on these sites, we really need to embed their JS to have them be effective.

I am also sensitive to being tracked on the internet, but people who are sensitive about this can pretty easily install a plugin that blocks it. We're not trying to do anything shady like route around user blocks.

And asking every user about this is not really a viable solution.

If anyone has other ideas, please share.

**Comment by NetOperatorWibby** [comment]
+1 on user doing the blocking. Anyone who hates Facebook/Google/&c are already blocking them. Maybe we could have a message to first-time visitors stating that we collect metrics in order to make site decisions.
