### ISSUE TITLE
Add facility for scheduling wallet transfer

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#1068]
We should be able to direct someone to a process that lets them claim their wallet other than email this address.

This could either be part of the YouTube status page or a separate page. It could use calendly or another tool that lets them pick a specific time for the transfer to occur and gives them instructions to follow in advance.

**Comment by kauffj** [comment]
@tzarebczan will set up a calendly link with valid standing times that anyone can pick

@NetOperatorWibby will add copy to you the youtube status page inviting people to use this link to book a time

**Comment by kauffj** [comment]
- @tzarebczan will build google form and redirect lbry.com/claim_wallet to the form
- After, @NetOperatorWibby updates youtube status page to mention form in some way

**Comment by tzarebczan** [comment]
Paul should have the link to the form from Slack. We probably need a short copy on the page itself. @Feanor78 can you work on that and the copy to the status page?
