### ISSUE TITLE
claim-wallet link changes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#1083]
- [ ] Remove from /youtube page

- [ ] add to /youtube/status page, and show only after they have agreed to sync.

**Comment by kauffj** [comment]
Drop 50k from form copy (@tzarebczan) and website copy (@NetOperatorWibby )

**Comment by NetOperatorWibby** [comment]
Closed via https://github.com/lbryio/lbry.com/commit/e90b3dc8153aec1eb23a6872ee9a0d4f56653497. I made changes and then tried to branch from master and messed up.

This is done though.
