### ISSUE TITLE
remove google analytics

### ISSUE THREAD

**Issue by catastrop** [lbryio/lbry.com#1084]
use a self hosted service like fathom or matomo

**Comment by catastrop** [comment]
??

**Comment by kauffj** [comment]
I appreciate this concern, but we're not going to do this now or in the near future.

We have no problem with you using and support you using browser plugins or 3rd-party tools that block GA or other 3rd-party services used by us.

**Comment by catastrop** [comment]
sad

**Comment by catastrop** [comment]
Bad

**Comment by catastrop** [comment]
not using your service
