### ISSUE TITLE
Pull tag descriptions from internal APIs

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#1090]
Tag descriptions are currently hardcoded in `MailActions`

**Comment by kauffj** [comment]
Use `/tag/list`

**Comment by kauffj** [comment]
@nikooo777 it looks like `/tag/list` is a restricted endpoint and lbry.com does not currently store any authentication credentials for api.lbry.com. 

Is it okay to add an auth_token for lbry.com to `config.php`? If so, who's should be added on production, yours? Maybe make a lbry.com account?

**Comment by kauffj** [comment]
@nikooo777 any thoughts on above?

**Comment by kauffj** [comment]
@nikooo777 I am putting my personal auth token in `config.php` and ansible config unless you stop me.

**Comment by kauffj** [comment]
Addressed in https://github.com/lbryio/lbry.com/pull/1097 but blocked by https://github.com/lbryio/internal-apis/issues/962

**Comment by nikooo777** [comment]
If this issue taught me anything it's that my email filters suck. I'll try to improve them to avoid this happening again.

On the other hand, the PR in internal-apis was merged (and I even reviewed it) so that https://github.com/lbryio/lbry.com/pull/1097 can proceed.

**Comment by kauffj** [comment]
Fixed in 16936bc7
