### ISSUE TITLE
Block reward source code non-existing link

### ISSUE THREAD

**Issue by danger89** [lbryio/lbry.com#1093]
#### Issue Summary

Link is not working on the FAQ page.

#### Steps to Reproduce

1. Go to: https://github.com/lbryio/lbry.com/blob/master/content/faq/block-rewards.md
2. Try to click on: https://github.com/lbryio/lbrycrd/blob/master/src/main.cpp

Properly you want to point to: 

- https://github.com/lbryio/lbrycrd/blob/master/src/validation.cpp#L2061
And/Or
- https://github.com/lbryio/lbrycrd/blob/master/src/pow.cpp#L75

**But I'm not fully sure!?!**

I don't know core code by heart, sorry. Hopefully somebody does without too much effort :+1:

**Comment by kauffj** [comment]
Thank you for raising this @danger89. The FAQ article has been updated (may take a few min to go live) and the correct link is https://github.com/lbryio/lbrycrd/blob/master/src/validation.cpp#L1025

**Comment by danger89** [comment]
Almost correct.. ><

**Comment by tzarebczan** [comment]
Thanks again @danger89, will send some LBC appreciation over on Discord
