### ISSUE TITLE
In the word library, y is a vowel

### ISSUE THREAD

**Issue by matj1** [lbryio/lbry.com#1107]
In [an answer in FAQ about the name of LBRY](https://github.com/lbryio/lbry.com/blob/master/content/faq/lbry-name.md), there is

> "Then why confuse people with the all-caps and no vowels?"

If Y in the word LBRY stands for y in the word library, it's a vowel, because in “library” it's pronouced /ɪ/ which serves as a syllable core. Even if “LBRY” is pronounced as one syllable, the phoneme represented by Y server as a syllable core.

I suggest the question would be changed to

> "Then why confuse people with the all-caps and removed vowels?"

That would not imply all vowels are removed, only some, although it's not a good wording and it could be done better.

**Comment by tzarebczan** [comment]
Hey @matj1, thanks for opening this issue and the suggestion. We'll review and take a look.

Can we show you some [appreciation](https://lbry.com/faq/appreciation)?

**Comment by kauffj** [comment]
I love this ticket

Fixed in https://github.com/lbryio/lbry.com/commit/d48aad8426293586363bf8382ccab3050535a6ec

**Comment by matj1** [comment]
I expected a discussion about what's the best wording of that sentence, but never mind.
