### ISSUE TITLE
Update contact on youtube sync page

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry.com#1108]
#### Issue Summary

https://lbry.com/youtube needs updating as Rob is still on the page as the contact

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry.com/commit/7adcd311bfeb52f5b20d6e0a65a9c1b1c022078f

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry.com/commit/b1d118b0136ad227d556df381b0c7e9cad818099

**Comment by kauffj** [comment]
Also cleaned up youtube status page post sync, it's a lot better with lbry.tv!
