### ISSUE TITLE
update supported types

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry.com#1118]
The list of supported types changed with the new player, i believe the list is out of date and could use a review: https://lbry.com/faq/how-to-publish

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry.com/commit/9420247ed0738b11a1b1d35b2dc92b40b96a6282 . We can revamp later to have a more concrete list of supported types, but the most common is video/mp4s.
