### ISSUE TITLE
Create FAQ for LBRY publishing standards

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry.com#1128]
#### Issue Summary

Create FAQ that specifies pixel sizes for:

- channel banners
- profile images
- thumbnails for videos

**Comment by tzarebczan** [comment]
These sizes are already referenced in the app. They can be added to the how-to-publish FAQ as well.

**Comment by tzarebczan** [comment]
At least on the desktop app...we probably need to do something similar for mobile. I shouldn't need to go to a faq to know this information.

**Comment by kauffj** [comment]
@tzarebczan agreed, but I think it may still be worth doing, because people will ask and until the SDK or apps enforce/encourage best practices, a resource article seems reasonable.

**Comment by tzarebczan** [comment]
First stab: https://github.com/lbryio/lbry.com/pull/1166
