### ISSUE TITLE
Words cut-off on window resize

### ISSUE THREAD

**Issue by deutranium** [lbryio/lbry.com#1131]
#### Issue Summary

The navbar text cutoffs on resizing the window as illustrated in the following screenshot:

![Screenshot from 2019-09-30 23-10-44](https://user-images.githubusercontent.com/29124655/65902873-f71fac80-e3d8-11e9-97b7-7ad39e98e009.png)

#### Steps to Reproduce

Resize the window horizontally, and notice how the text wraps to the next line just before switching to the mobile-like view

If it's fine, then I would like to work on this as a part of Hacktober Fest

**Comment by jsigwart** [comment]
I have added the Hacktoberfest label for you. :)

**Comment by kauffj** [comment]
Great catch @deutranium, this is entirely appropriate!

**Comment by liloo2040** [comment]
Hello! May I help you on this issue ?

**Comment by kauffj** [comment]
@liloo2040 and/or @deutranium either you are welcome to work on this, though I just tried and could not reproduce it. It is possible this was a bug that was temporarily live for only a few days when we accidentally deployed some broken JS.

**Comment by deutranium** [comment]
@kauffj I can still reproduce the bug, but I am not able to reflect the changes made in web/components/sass/navigation/_index.scss in the webpage

**Comment by liloo2040** [comment]
Ok, I've seen the issue. I'm working on it.

**Comment by ykris45** [comment]
@deutranium how to reproduce and notice on how the text wrapped in to mobile view?. i still not found this bug on my local machine?

**Comment by tzarebczan** [comment]
This has been fixed.
