### ISSUE TITLE
email preferences page broken

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#1143]
`Uncaught SyntaxError: Unexpected end of input `

**Comment by kauffj** [comment]
@lyoshenka https://github.com/lbryio/lbry.com/commit/b181563aba3728e212ebeca2b7d08fd5745af6c6 was improperly processing/munging the search JS in `_header.php`, resulting in pages with improperly terminated output.

I disabled this behavior for now.

**Comment by lyoshenka** [comment]
fixed
