### ISSUE TITLE
Expand content reporting (and move into lbry.tv?)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#1193]
Users should be able to report content to the community for flagging beyond just for DMCA

**Comment by HarshKhandeparkar** [comment]
I would want to work on this. If we want to integrate this with lbry.tv then we would have to implement a POST API here or somewhere to process the emails, right?
@kauffj

**Comment by Eniamza** [comment]
Apart from High level thinking. As the form only sends a link. Cant we implant a simple HTML form and then automate the sending process with zap intefrations?

**Comment by HarshKhandeparkar** [comment]
lbry.tv is all JS and frontend. JS runs on the client side so it can't send emails. Only the PHP code (server side) can.

**Comment by Eniamza** [comment]
docment.getelementbyID . That would pull informations from The form and send it

**Comment by HarshKhandeparkar** [comment]
Should we discuss it in discord?
