### ISSUE TITLE
Make LBRY's DMCA takedown system far better than youtube's

### ISSUE THREAD

**Issue by mario2582** [lbryio/lbry.com#1196]
Make LBRY's DMCA takedown system far better than YouTube's

some things that should be implemented into your DMCA system to make it far better than YouTube's crappy robotic version. 

- Require a photo captcha and a scan of the person's ID who files a DMCA takedown notice and same thing with counterclaims to prevent fraud from DMCA extortionists. 

- REQUIRE Plenty of Paperwork / Sources to prove if a DMCA takedown filer does indeed owns copyrights to something. 

- Use humans to filter out incomplete DMCA claims and counterclaims. ANYTHING properly written like in the counterclaim in the image below should be ALLOWED to PASS THROUGH ONTO THE CLAIMANT without restriction.

- Add some special area to allow someone to post evidence of report DMCA fraud from a DMCA scammer extortionist. Mainly used to contact and report to LBRY if a DMCA extortionist scammer files a false DMCA claim against you (example scammer files to bogus DMCA claims to give a user two strikes on youtube and forces user to Pay something like $384 via bitcoin through spoofed email or they will file another notice and give your youtube channel the 3rd strike)

- **DO NOT IMPLEMENT ANY KIND OF AUTOMATED SYSTEM TO HANDLE both DMCA NOTICES AND COUNTER NOTICES EVER**. You real human employees. If you do this with AI, you will end up just like YouTube with this automated crap. You are required by DMCA LAW in the DMCA to allow counter-notices to pass off to the claimant if they're written properly like this one in the image is.

![dmca bogus](https://user-images.githubusercontent.com/11165643/70590784-c068ce00-1ba1-11ea-9452-14f0450f1ce0.jpg)

STAY AWAY FROM AND DO NOT implement a 3 copyright strikes and your out and your terminated system like YouTube, Instead for infringers LBRY should take a MUCH LIGHTER handed approach instead of permabanning them from the LBRY website for 3 or more copyright strikes, instead of deleting videos that receive a DMCA claim and issuing a copyright strike, force those videos or anything that receives a DMCA claim to be forced to encrypted and private so that only the original uploader can view / download it on lbry until the copyright takedown notice is either resolved by a counter-notice or the user deletes the video / thing that received a DMCA claim. This kind of design will prevent trolls from abusing the system to take down someone's channel while allowing a media company to force a video that is obviously infringing to remove that video from "being seen on the platform"

DO NOT IMPLEMENT ANY FORM OF SYSTEM OF CONTENT ID like youtube! It's ripe with MISFINDS, ERRORS, AND ABUSE.

**Comment by tzarebczan** [comment]
Thanks for the feedback and write-up. We currently process dmca claims manually, there's no automated system. We also can't delete content, we can only block it.

Please see LBRY.com/faq/dmca for more details. Closing this for now as there's no immediate action we'll be taking. 

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the feedback?

**Comment by mario2582** [comment]
> Thanks for the feedback and write-up. We currently process dmca claims manually, there's no automated system. We also can't delete content, we can only block it.
> 
> Please see LBRY.com/faq/dmca for more details. Closing this for now as there's no immediate action we'll be taking.
> 
> Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the feedback?

Stay away from the 3 strikes copyright system with LBRY. Hiding videos from everyone except the original uploader that receives a DMCA takedown notice is a better idea until the original uploader files a counterclaim or contact's LBRY with documentation that shows why the claim is bogus such as if it came from someone who does not actually own the copyright or a DMCA takedown extortion scammer.
