### ISSUE TITLE
March a Million: Reward Reminder

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#1247]

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/growth #554](https://github.com/lbryio/growth/issues/554) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/growth #555](https://github.com/lbryio/growth/issues/555) via [**ZenHub**](https://www.zenhub.com/)
