### ISSUE TITLE
Fix meta image on Twitter for lbry.com/get

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#1252]
https://twitter.com/LBRYio/status/1255248879815188481

**Comment by kauffj** [comment]
Either the page for no system or Android is messed up

**Comment by littlemadhatter** [comment]
Took a look at this, below are meta tags you should be able to incorporate into the site for it to pull correct meta tags, readable more at https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary

```
<meta name="twitter:card" content="summary" /> (Do not change)
<meta name="twitter:site" content="@LBRYio" /> (not required, though)
<meta name="twitter:title" content="LBRY, a decentralized content platform" />
<meta name="twitter:description" content="LBRY is a content platform owned by everyone (and no one)." />
<meta name="twitter:image" content="link" /> (read more about image at the link beforehand)
```
You can't test beforehand until the URL is live unless I skipped that part
