### ISSUE TITLE
Problems deleting an old channel in order to synchronize a new channel with youtube

### ISSUE THREAD

**Issue by kolorionstudio** [lbryio/lbry.com#1267]
When you follow the FAQ instructions in the transaction history, the trash icon does not appear to delete the channel.

It would be nice from the interface in channel configurations to have the option to delete the channel, configuring validate password to delete it.

**Comment by tzarebczan** [comment]
Sorry to hear. We'll be adding it there soon.

Did you filter on channels? If there's no trash can icon, it means it's probably deleted

**Comment by kolorionstudio** [comment]
The channel still exists ... and it doesn't have the stationery icon.
I put the history in everything only the garbage can icon appears from the first publication onwards.

I just connected my youtube account with the same name of the channel created previously, will it be for that reason that I can not?

**Comment by tzarebczan** [comment]
Can you share a screenshot of the channels + active page to hello@lbry.com

**Comment by kolorionstudio** [comment]
thanks
