### ISSUE TITLE
Telegram bot does not exist any longer

### ISSUE THREAD

**Issue by Geordon** [lbryio/lbry.com#1304]
#### Issue Summary

The Telegram bot mentioned [here](https://lbry.com/faq/bot-telegram) is not available on Telgram.  Has it been deleted? Does it need to be restarted?  

#### Steps to Reproduce

1. https://telegram.me/LBRY_telegram_bot and allow web browser to open Telegram 
2. See message from Telegram that this user does not exist

**Comment by tzarebczan** [comment]
It's been removed for now, we'll bring it back later.
