### ISSUE TITLE
Capital C Credits

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#1336]
Audit all copy for this

**Comment by ykris45** [comment]
This Special Task From Mr @kauffj Was Finished By Chris From Indonesia.

**Comment by ykris45** [comment]
#1407

**Comment by kauffj** [comment]
thank you @ykris45!

**Comment by ykris45** [comment]
> thank you @ykris45!

You Welcome sir. Memeking always Help for LBRY Universe
