### ISSUE TITLE
Feature request: an obvious and effective mechanism for closing accounts

### ISSUE THREAD

**Issue by Paraphraser** [lbryio/lbry.com#1348]
I had great hopes for lbry but I'm giving up. I've had my fill of the laborious five-step mechanism to login:

* TYPE your email address by hand, each time, because, guess what, auto-fill does not work (why?)
* WAIT **minutes** for the email to arrive (why?)
* CLICK the link in the email which contains an outright **lie** that this is a **new location** when it is the **same** iPad I **always** use, connected to the **same** network I **always** use, sitting in the very **same** spot on the planet I **always** use to watch videos on my iPad (I thought Apple had the monopoly on claiming their very own device was "new" when it had actually been used by Noah to allocate Ark berths;  this is the wrong model to emulate)
* CLOSE the totally unnecessary extra browser tab that gets opened as a result
* FORGET what caused you to want to open the lbry page in the first place.

There needs to be an obvious easy-to-use feature in the web interface via which any frustrated user can close his/her account to clearly signal "lbry begone! Any and all LBC can be routed to an insolation-free zone". A FAQ entry is not quite enough (although it is evidence suggesting such a UI feature would find use among however many users have asked this question in order for it to reach the status of "frequent"). Requiring an email to request a manual removal simply adds insult to injury.

**Comment by tzarebczan** [comment]
Thanks for the feedback. Since we don't have access to user accounts, we have to make it clear to them that they need to delete any channels or content that they may have, and move any LBC they don't want to lose. 

In the future we hope to make this more automated somehow.
