### ISSUE TITLE
Problems of description and link in an FAQ article

### ISSUE THREAD

**Issue by ONLYA** [lbryio/lbry.com#1353]
The problems come into two sections: description and link.

### Description problem
In [the last section in an FAQ article](https://github.com/lbryio/lbry.com/blob/master/content/faq/what-is-lbry.md#user-content-this-is-amazing-take-my-money), there is a sentence:

> We have _bad_ news for you, you can use LBRY for _free_.

It seems like there is a contradiction in that sentence. What do you mean by "Bad news because of free service"? Should it be
>We have _good_ news for you, you can use LBRY for free.

or
>We have bad news for you, you can _not_ use LBRY for free.

### Link problem
The first 4 of the 5 links in the article are not valid.

**Comment by tzarebczan** [comment]
It's a joke :)
