### ISSUE TITLE
Team Page Image Sizes too Small

### ISSUE THREAD

**Issue by ElectronEsq** [lbryio/lbry.com#1355]
#### Issue Summary

The image sizes on the Team page are too small, so when the browser enlarges them to fit the containing area, they are very pixelated.

#### Steps to Reproduce

See [LBRY Team](https://lbry.com/team)

![image](https://user-images.githubusercontent.com/29914179/101714481-64eb5c00-3ae5-11eb-9b4e-bfcd3ecd12f4.png)

**Comment by tzarebczan** [comment]
We're experimenting with a CDN and compression was set too high - can you check again now? Please re-open if you think we should still adjust.

**Comment by ElectronEsq** [comment]
Yes, much better now.

However, there was a issue on Odysee too. Not sure if it's the same issue but it looks like it. Thumbs were being shrunk there also, thus became blurry and pixelated.

![image](https://user-images.githubusercontent.com/29914179/101790976-c1369600-3b4e-11eb-9ef1-773a752b1ea6.png)

These will be cached by Facebook and Twitter etc indefinitely, so they wont fix when the issue is fixed. But there is a trick you can do in social media developer tools to release them from the cache. So if anyone needs to get the better thumb showing after the fix, they can do this.



## Facebook Example - It's a similar process for most social media platforms.

1. Go to 
2. Ender your post address in the to input box.
3. Press Scrape Again.

![image](https://user-images.githubusercontent.com/29914179/101792284-3fe00300-3b50-11eb-8ab4-1aa9a6f43cdf.png)

![image](https://user-images.githubusercontent.com/29914179/101792298-44a4b700-3b50-11eb-8c5b-ec0aeca9f777.png)

## Still Broken

In the case, the image is still too small, so it returned an error. But when the issue is fixed, I'll run this again and it should fix the issue.

![image](https://user-images.githubusercontent.com/29914179/101792343-52f2d300-3b50-11eb-824b-1f417c9dea2c.png)
