### ISSUE TITLE
Link Odysee beta at /ios

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#1360]

**Comment by kauffj** [comment]
@julianchandra attach preferred image here

**Comment by julianchandra** [comment]
![Uploading image.png…]()

**Comment by julianchandra** [comment]
![106070488-6e01bc80-6169-11eb-9e09-f594027367b8](https://user-images.githubusercontent.com/67612037/108098908-caede580-7038-11eb-8967-60687dafbfbd.jpg)

**Comment by julianchandra** [comment]
@kauffj try now
