### ISSUE TITLE
Better subscribed channels organization options

### ISSUE THREAD

**Issue by tryfon** [lbryio/lbry.com#1364]
According to my experience, a huge issue I had with YouTube was that it was very hard to browse my hundreds of subscribed channels as the platform gave no option to the user to organize them in categories etc, and instead it preferred to feed them to me however it wanted (for obvious reasons) or in the best case in alphabetical order. My solution to this was to export the .oml file of my subscriptions and import it in a tool like Feedly and follow my preferred content from there. See the screenshots to understand my point of view.
As it is, Odyssey interface doesn't offer any big advantages over YouTube in this, it is practically the same. I believe more options for organization and categorization should be given to the user.

![Capture](https://user-images.githubusercontent.com/4881561/105830525-43c7c780-5fce-11eb-8422-38ef8eb44bfa.PNG)

**Comment by tzarebczan** [comment]
Thanks for the issue! We've got this filed as a feature request on the main repo for lbry.tv/desktop/odysee: https://github.com/lbryio/lbry-desktop/issues/4093
