### ISSUE TITLE
Impossible loop for rewards approval between discord and phone. Maybe consider a telegram group for rewards approval

### ISSUE THREAD

**Issue by Librebowski** [lbryio/lbry.com#1368]
It seems its possible to be locked out of enabling rewards if someone else has verified with your phone number previously and simultaneously Discord is known for their terrible anti-spam algo thats banhammer heavy. I have never even used the site (discord) and yet I'm instantly banned for having a "secure" internet connection. 

I may have been banned for having a VPN who knows but either way, like I said, it's nothing I have done as I have never even used the site before. I can't get through any of these verification options. I'm stuck, it's very frustrating.

Please consider offering support on telegram or somewhere else. I mean anything is better than discord.

![screen](https://user-images.githubusercontent.com/26209956/106972048-1988af00-671e-11eb-8a96-c610cd3dc7b9.png)

![buubyby](https://user-images.githubusercontent.com/26209956/106972684-51dcbd00-671f-11eb-8f92-dd81e1670320.png)

**Comment by tzarebczan** [comment]
Please send us an email at hello@lbry.com to find out what your previous account was that's linked to that phone number. Or unless you know it, then please use that. 

The link at chat.lbry.com and chat.lbry.org should work, just tested it. Not sure why yours says expired. 

Sorry for the trouble!
