### ISSUE TITLE
YouTube sync for non-youtubers (subscription sync)

### ISSUE THREAD

**Issue by RubenKelevra** [lbryio/lbry.com#1370]
#### Issue Summary

It's quite a hassle to search for all the YouTubers you love which might already be syncing their content to lbry. There should be an easy way for the end-users who mainly consume videos to migrate the subscriptions and keep them up to date. 

All creators which start to sync their youtube channel to lbry will get the subscriptions of users there, which avoids that the users need to find out that the youtubers switched to lbry. The users should get additionally a notification, to inform them about this.

#### Steps to Reproduce

1. Subscribe to hundreds of channels on youtube
2. Create a Lbry account
3. Have to manually search for each subscription you made on youtube.

**Comment by cytsunny** [comment]
Seems this extension has the function you needed?

https://github.com/LBRYFoundation/Watch-on-LBRY

**Comment by RubenKelevra** [comment]
Yes and no. It's a manual process with this extension which is extremely cumbersome. You need to
- ask google for some data
- wait for an email
- do security login with google
- download a file
- unzip it
- upload it on the "website"
- and you end up with a list of links you need to click through and subscribe on each of them.

Why not let people login and request the subscriptions once a day and send them notifications that they are now subscribed to their beloved YouTubers on lbry, too? :)

**Comment by tzarebczan** [comment]
It may be tricky due to youtube api limitations, but we'll see! 

https://github.com/lbryio/lbry-desktop/issues/5173 is filed for it.

**Comment by RubenKelevra** [comment]
@tzarebczan maybe it makes more sense to include this in the desktop client in this case? The client could act like any other YouTube client and fetch a list of subscriptions. This would also be more distributed :)
