### ISSUE TITLE
Incorrect Tax Guidance

### ISSUE THREAD

**Issue by iamjameswalters** [lbryio/lbry.com#1371]
From `creator-tax-obligations.md` :

> In the US, IRS reporting is only necessary if you earned more than $600 USD/yr, so it would not apply to majority of regular users or smaller creators.

This is incorrect, it is necessary to report all income to the IRS. The $600 threshold is only for whether or not the payer (presumably LBRY) must file this in a 1099-MISC.

Can we please update this tax guidance to be correct? Hopefully much sooner than later LBRY will be able to export a CSV that is compatible with common crypto tax software (e.g. TaxBit, Koinly, etc).

**Comment by finer9** [comment]
yes, sorry, you are right, fixing!

**Comment by finer9** [comment]
and yes we are absolutely working on a report  to make this easier for creators

**Comment by iamjameswalters** [comment]
Thanks for fixing this @finer9 ! An LBC is on its way.

Good to hear! I understand it may not be possible to prognosticate about when that feature will be ready, but would you have any indication? In particular, I'm hoping it will be available before April 15, 2022.
