### ISSUE TITLE
Get rid of cloudflare

### ISSUE THREAD

**Issue by Kreyren** [lbryio/lbry.com#1380]
Cloudflare made the website unusable for me as it requires me to perform captcha each time i try to visit.

![image](https://user-images.githubusercontent.com/11302521/115132415-3a179400-a000-11eb-8f59-0f52899a6f6b.png)

**Comment by Kreyren** [comment]
Why was this closed?

**Comment by JasonTable** [comment]
dunno. it seems pretty rude of them to not even give a explanation.
