### ISSUE TITLE
Bittrex delisted LBC

### ISSUE THREAD

**Issue by m971668** [lbryio/lbry.com#1412]
Bittrex has delisted LBC markets.  One cannot buy or sell LBC via Bittrex anymore.

This needs to be changed to reflect that:
https://lbry.com/faq/buy-sell-bittrex

https://bittrex.zendesk.com/hc/en-us/articles/360058775712-LBC-Market-Removal-04-16-2021

**Comment by tzarebczan** [comment]
That's not for US users, which is clarified in the FAQ. LBC is still listed on Bittrex global.
