### ISSUE TITLE
odysee.com - where are files stored and how are distributed

### ISSUE THREAD

**Issue by slrslr** [lbryio/lbry.com#1415]
Hello,
as a newbie i was wondering where are https://odysee.com videos stored and how are distributed among users, so in the hamburger menu i click About and on the opened page https://lbry.com/faq/what-is-lbry i am unable to find out the answer to that question.

https://github.com/lbryio/lbry.com/blob/master/content/faq/what-is-lbry.md

I was also wondering how much i need to pay to view the videos, because it cost money (LBRY Credits?) to seed the video. And to pay, i would need to make the money somehow.

**Comment by tzarebczan** [comment]
Please see lbry.com/faq/host-content for more details about this. There are no hosting incentives or fees at this time.
