### ISSUE TITLE
Add video signature and owner verification to erase duplicates from youtube video imported

### ISSUE THREAD

**Issue by Guigeek973** [lbryio/lbry.com#1445]
Hello,

I don't know where to post my suggestion, I think it is very necessary to get more value on the product.
I've just discovered the rapid growing website and project odysee (lbry) with grat and intuitive design !

#### Steps to Reproduce

1. Open odysee.com search for a video that is also on youtube.com and has many views
2. Click on this video and see the related videos at right side of the screen
3. You will see many duplicates of the videos published by different odysee accounts

Maybe it's not the website who handle this... A way to suggest this to the odysee team that works on backend ?

**Comment by tzarebczan** [comment]
Thanks for filing the issue. Some content may not have copyright and owners are encouraged to submit reports of any value copyright claims.
