### ISSUE TITLE
Is there a reward for automatic rehosting on port 5567?

### ISSUE THREAD

**Issue by poikilos** [lbryio/lbry.com#1448]
#### Issue Summary

Does forwarding port 5567 add rehosting rewards while the LBRY background service is running? I don't want to risk getting throttled by an ISP unless I'm sure there is:
1. a reward
2. a way to limit upload bandwidth (if not, I can schedule the process to only run a couple hours per day or something
3. automatic rehosting (Does leaving the background process running keep on rehosting when there are incoming connections even if I merely watched the video and it is in cache, and I did no extra step to repost it?)

2 only matters if 1 is true. If not, I'd just not forward port 5567 (I don't enable UPnP so this would not get forwarded unless I forward the port manually) since there would be risk (possibly getting throttled) and no reward.

**Comment by tzarebczan** [comment]
1) There is not, something planned for the future. 
2) It's coming in a few months
3) Yes 

And it's port 3333 for hosting - see lbry.com/faq/host-content
