### ISSUE TITLE
Mac Docker Setup Broken

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry.com#297]
I'm using Docker version 17.09.1-ce on macOS Sierra 10.12.6. The `docker.sh` script doesn't work. This seemed to mostly work

```
#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
scriptDir="$(cd "$(dirname "$0")" && pwd -P)"

echo $scriptDir


if [ ! -e "data/config.php" ]; then
  cp "$DIR/data/config.php.example" "$DIR/data/config.php"
fi

docker run --rm -it --name "dev.lbry.io" \
  -v "${scriptDir}:/usr/src/lbry.io" \
  -w "/usr/src/lbry.io" \
  -p "127.0.0.1:8000:8000" \
  -u "$(id -u):$(id -g)" \
  php:7-alpine \
  php --server "0.0.0.0:8000" --docroot "web/" "web/index.php"
```

But then it said that the directory `web/` could not be found. I am not sure how to fix this, I have instead opted to run with just php for now which works fine.

**Comment by lyoshenka** [comment]
This script was added by an outside contributor. It probably needs to be updated or removed, since I don't think any of us use it.

**Comment by kauffj** [comment]
@flungo are you interested to fix this?

**Comment by flungo** [comment]
I'll take a look at the weekend make sure it still works on Linux and see if there is anything I can spot that would mean it doesn't work on Mac although I do not have a Mac to be able to test/confirm compatibility.On 16 Jan 2018 21:21, Jeremy Kauffman <notifications@github.com> wrote:@flungo are you interested to fix this?

**Comment by flungo** [comment]
Made a patch (#328) which should be compatible with MacOS.

@liamcardenas could you please checkout my fork and confirm that this now works for you?

Bear in mind #327 which will mean you should set `$config['is_prod'] = "yes";` in `data/config.php` or change `php:7-alpine` to `php:7.1-alpine` in the `docker.sh` script to be able to see the site correctly until the deprecated function is removed or compatibility is specified as `>=7.0 <7.2` and I'll update my PR to reflect this by making the change described here.

**Comment by liamcardenas** [comment]
Hi @flungo awesome that you are working on this, unfortunately, I no longer have MacOS. Do you need someone else to test? or are you just trying to verify that my exact problem is not reoccurring.

I have access to a Mac, but it is not the same one that originally had the error.

Let me know if there is anything I can do.

**Comment by lbrydocs** [comment]
I suspect it might have been my setup that triggered this - I had problems with another package, a friend helped me through it. Let me see if my current setup behaves.

**Comment by lbrydocs** [comment]
I have a Mac running 10.13 and I have Parallels, so I can roll out older version of the OS without too much trouble.

Is there a very specific goal here? Like, has to work with 10.13 and 10.12? There is a limit to how far back I can go, it's based on what App Store will permit for downloads based on hardware.

**Comment by alyssaoc** [comment]
@tzarebczan Can we close this?
