### ISSUE TITLE
Generate new FAQ(s) based on Jeremy's email Q&A

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#316]
Q. Is anonymous publication possible?  How is anonymity accomplished?

A. LBRY does not log

Q. What are the privacy mechanisms?  Specifically:
  - Can publishers be connected to real-world identifiers, such as IP addresses?  If not, how do you authenticate users so they can maintain control of their content?

A. Yes, if they choose to provide this info. Some of this is still in the works, they're closer to pseudonymous identities currently, though we believe we can support fully verified ones.

Q. Can downloaders be connected to real-world identifiers?

A. Similar to BitTorrent. You can observe IPs.

Q. Is LBRY resistant to firewalls as found in China or Iran?

A. Somewhat unclear. It is likely sophisticated enough software could detect LBRY and stop usage of it, though if this happened we could also evolve things on our end, turning it into a fun game of cat-and-mouse. A lot of the traffic basically ends up looking like random encrypted UDP requests.

Q. What information do you retain that could be subpoeaned?

A. The current software makes some analytics calls that are discarded after several months but are technically subpoenable and could likely be used to prove certain activities. This can be turned off though. Other than this, none.

Q. In whose legal jurisdiction are your servers located?

A. The point of the LBRY protocol is that our servers are not required for it to operate.  Though given the youthful state of the network, we do choose to operate some to ensure good performance, and they're located in the US.

**Comment by ykris45** [comment]
i will make a draft of this FAQ.

**Comment by tzarebczan** [comment]
@jsigwart assigning this one to you since you were working on privacy-related FAQs.

**Comment by alyssaoc** [comment]
@jsigwart Are these still pending with the privacy policy?

**Comment by kauffj** [comment]
Who is this blocked by or waiting on?

**Comment by jsigwart** [comment]
This one appears to ultimately go back to issues blocked by the Data Retention Policy, see growth #1 68?

**Comment by Feanor78** [comment]
@jsigwart @kauffj what's the story with this ticket?

**Comment by jsigwart** [comment]
# Privacy Policy Stuff

Adding notes to this ticket for clarity on small swarm of circular tickets/issues:

## Issues
Create lbry-privacy.md #932 https://github.com/lbryio/lbry.com/pull/932 - CLOSED, not merged - was first stab at Privacy FAQ
Privacy FAQ #168 https://github.com/lbryio/growth/issues/168 - OPEN
Data Retention Policy https://github.com/lbryio/lbry.com/issues/316 - OPEN


## Current relevant resources 
Privacy Policy: https://lbry.com/privacypolicy last edited 4/28/18
AUP: https://lbry.com/faq/acceptable-use-policy

https://docs.google.com/document/d/1fCKYJEYzTz5nKgmCUVb3BqRD5vioGB45cEc5j9souaE/edit - this is labeled Privacy Policy but is actually Data Retention Policy

- Original issue of not having a Privacy Policy was resolved when lbry.com/privacypolicy was finally published
- Two issues remain: 
	- Privacy FAQ
	- Data Retention Policy
