### ISSUE TITLE
SEO and social metadata clean up (rel=canonical and og:url)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#350]
Two related issues:

### Missing `rel=canonical` on identical pages

@tzarebczan inadvertently pointed out that the following URLs serve the same post:

https://lbry.io/news/lbry-development-community-update-jan-2018
https://lbry.io/news/159-lbry-development-community-update-Jan-2018

At a minimum, blog post pages should include a `rel=canonical` tag pointing to the best URL (just the slug, no numbers, all lower case).

In addition, alternative URLs could be redirected to the preferred URL.

### Include og:url

Add an og:url tag that matches the `rel=canonical` URL, or the URL of the accessed page if there is no canonical URL

**Comment by Invariant-Change** [comment]
## og:url still missing.

`Missing Properties: The following required properties are missing: og:url`
https://developers.facebook.com/tools/debug/sharing/?q=lbry.io

**Comment by mevrouwdevries** [comment]
I'd like to work on this issue. Please assign me?

**Comment by windofrebel** [comment]
sadece yorum yapmaya geldim.
