### ISSUE TITLE
Determine if any disclaimers, links, policies, etc. should be in website footer

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#369]

**Comment by jsigwart** [comment]
We need to add Terms of Service and Privacy Policy. When I was looking at making the AUP, I saw you requested it be made as a FAQ file, so I did it as a markup document. 

We have a stub for ToS and it lives in the view/templates/page directory. Do we want to create ToS and Privacy Policy as individual pages there, or is there any plan to create a more generic way to manage these pages? Right now the SEO on the FAQ pages isn't quite ideal, either as the Title and the Meta Description are the same - the FAQ title of the page.

**Comment by kauffj** [comment]
@jsigwart I suppose these could simply be FAQ articles rather than independent pages. I'm fine either way.

Re: SEO, you can set meta and social info by adding any of the following lines to the template code. Traditionally these are added at the top of the file:

```
<?php Response::setMetaTitle("This is the title the page will be given in search results and when shared on social media.") ?>
<?php Response::setMetaDescription("This is a description that will show in search results and social media") ?>
<?php Response::addMetaImage(Request::getHostAndProto() . '/img/lbry-ui.png') ?> //This will set the image shown when the page is shared socially
```

Yeah, I realize this isn't particularly user-friendly, especially the last line.

**Comment by jsigwart** [comment]
That also defeats the purpose of having a yaml file for internationalization.

**Comment by kauffj** [comment]
@jsigwart you can also use the `i18n` calls inside of those, e.g.

```<?php Response::setMetaTitle(__('page.meta.title.')) ?>```

**Comment by jsigwart** [comment]
I understand that. What I'm getting at is basic website structure and content management: are we going to make FAQ the default place to dump content, having it become huge scrolling page like the news section? Or do I set up individual pages in the templates folder (seems silly), or will we add a page management system to manage md files similar to how the FAQ handles? And then pagination of long scrolling pages to make them more easily viewable? I want to get the awkward under control.

**Comment by kauffj** [comment]
Ah, my mistake. What do you think, is it more appropriate that this be a standalone page or a FAQ article?

(Related: perhaps it's more appropriate to call the FAQ a KB).

Both of the following are possible:
- Changing the FAQ page to better handle a large number of documents
- Adding support for a page that is just a markdown file (though this limits what you with the page, it's relatively easy technically)

**Comment by jsigwart** [comment]
My thought about what is best right now is to make the ToS and Privacy Policy as FAQ pages (so we can do them in markdown) and get those linked in the footer, then revisit website structure later. See comments in #391 re: new FAQ category.

**Comment by DiSae** [comment]
Could the headquarters address or general contact info be added to the footer or anywhere more visible please?
The only page I could found the HQ address on the website is https://lbry.io/faq/contest-t-and-cs
Another possibility is adding it to the 'About the team' page.
