### ISSUE TITLE
Release full terms of service

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#430]

**Comment by kauffj** [comment]
Where is the new/proper ToS?

**Comment by jsigwart** [comment]
Internal doc at this point, needs many details: https://docs.google.com/document/d/1QYUijDq9MKoRSci4HpSfIhCPQYoODcyS0SnK4orYTuk/edit?usp=sharing

**Comment by alyssaoc** [comment]
@jsigwart is this in progress? What is the status?

**Comment by jsigwart** [comment]
Blocked, need input from exec level. Some parts in the ToS reference future features that have not been added to the app/protocol (and we don't necessarily know the details of how those features will be implemented).

**Comment by kauffj** [comment]
I'm not convinced that a ToS is even necessary here. But this should be in @finer9 court.

**Comment by jsigwart** [comment]
@kauffj where would you think it would be appropriate? The app itself? Also LBRY.fund. What about how it applies to community contributions to our public repositories, including this one?

**Comment by kauffj** [comment]
Whether it is literally a terms of service or not, I think there are some aspects of the LBRY protocol that are important for a publisher to be aware of before submitting a publish to a blockchain node. So I would support some kind of acknowledgement anywhere a publish can happen from.

I do not see a strong reason to put it anywhere else, but could be overlooking one.

**Comment by jsigwart** [comment]
Spee.ch TOS should be done at the same time. Added issue https://github.com/lbryio/spee.ch/issues/571

**Comment by alyssaoc** [comment]
@finer9 Can you please evaluate this issue please

**Comment by finer9** [comment]
[LBRY Terms of Service.DOCX](https://github.com/lbryio/lbry.io/files/2443394/LBRY.Terms.of.Service.DOCX)

**Comment by finer9** [comment]
Here is the plan, please comment @kauffj @jsigwart 

1. I will go through the DOC from Perkins and see how many blanks I can answer
2. I will identify the questions requiring more input and first come to @kauffj 
3. If there are questions requiring it, I will loop in Perkins
4. When complete, this should work for both the lbry app and spee.ch - since they serve similar functions
5. It is possible we still need a ToS for lbry.io itself - which would be a standard website ToS not about publishing/app functionality

**Comment by finer9** [comment]
@kauffj it would be great if you could address the highlighted sections and we could get something in place at least. I can try and do another round of edits after you comment. Alternative is back to Perkins

**Comment by kauffj** [comment]
Google doc reviewed.

**Comment by finer9** [comment]
This is back to me and I will have a TOS for both speech and the library app soon.

**Comment by finer9** [comment]
Made a bunch of updates, this is now 80% done pending a discussion with @kauffj

**Comment by finer9** [comment]
Still waiting on Perkins memo to finish this off

**Comment by alyssaoc** [comment]
@finer9 Have we gotten the memo to finish this?

**Comment by jsigwart** [comment]
Do we have a status on this?

**Comment by kauffj** [comment]
This is for @finer9, right?

**Comment by finer9** [comment]
I have been blocked by some money transmitter stuff but am going to just
put out a version we can use in the meantime

**Comment by kauffj** [comment]
https://lbry.com/termsofservice needs to be updated to whatever it is

**Comment by kauffj** [comment]
@finer9 are you working on this?

**Comment by finer9** [comment]
The ToS doc is done, if someone wants to put it on our website.

**Comment by kauffj** [comment]
@finer9 can you link this document in Slack to myself and @jsigwart?

**Comment by jsigwart** [comment]
Is it still this document or did it move elsewhere? https://docs.google.com/document/d/1wbTRhojo05kZkXpjxCCJEmtyJvxEjbAFfINTWS1foXU/edit#heading=h.gjdgxs

**Comment by finer9** [comment]
Yes that is it

**Comment by kauffj** [comment]
@kauffj to review/edit google doc

**Comment by kauffj** [comment]
I read this and left the comments I have.

**Comment by kauffj** [comment]
Add link to website footer before marking this complete

**Comment by jsigwart** [comment]
DONE!! https://lbry.com/termsofservice
