### ISSUE TITLE
Add consistent URL for LBRY Android build artifact

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#499]
LBRY Android binaries should have consist URLs similar to app releases.

See: https://github.com/lbryio/lbry.io/blob/master/controller/Controller.class.php#L179

Discuss with @akinwale and possibly @IGassmann how and where these will end up.

**Comment by alyssaoc** [comment]
@akinwale Has this been addressed? Can it be closed?

**Comment by kauffj** [comment]
Fixed in 4362f7b6
