### ISSUE TITLE
Drop case sensitivity in URLs

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#556]
lbry.io/reefermadness and lbry.io/ReeferMadness should both show the same page

Additionally, this ticket should not be considered complete without `rel=canonical` meta tag so that both count the same for SEO purposes.

**Comment by tzarebczan** [comment]
Related: https://github.com/lbryio/lbry.io/issues/350

**Comment by kauffj** [comment]
Be sure to not do this for URLs that include tokens. It's primarily for dynamic and fixed pages.

**Comment by NetOperatorWibby** [comment]
This is no longer an issue _locally_. I am able to visit `http://localhost:8000/vit` and `http://localhost:8000/VIT` without issue.

`https://lbry.com/VIT` fails while `https://lbry.com/vit` works just fine.

Seems like a server issue at this point.
