### ISSUE TITLE
YouTube Sync: show reward claimed for current period

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#565]
![youtubesync](https://user-images.githubusercontent.com/8120721/40184965-82d68d3e-59bf-11e8-8df6-116be287ac0f.jpg)

Currently, the status page does not reflect that a Sync reward has been claimed as the last step never gets a green checkbox. Not sure if this should reset when they can earn the reward again.

In this case, we may also want to update the expected rewards portion - maybe give them the date when they can earn this reward again? 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by nikooo777** [comment]
@kauffj who can we assign this to?

The API will provide `redeemed_reward` that can be used to solve this.
Sounds like a rather easy improvement.

**Comment by kauffj** [comment]
@nikooo777 open a ticket on `lbry.io` and put it in the `Next Sprint` milestone.

**Comment by nikooo777** [comment]
let's use this issue then. it's already in lbry.io

**Comment by NetOperatorWibby** [comment]
[This is already live](https://github.com/lbryio/lbry.com/blob/master/view/template/acquisition/youtube_status.php#L10).

<img width="1189" alt="Screen Shot 2019-04-15 at 11 51 51 AM" src="https://user-images.githubusercontent.com/1288356/56150657-f0a98f80-5f74-11e9-9d08-0ea48b168685.png">

Am I missing something?

**Comment by tzarebczan** [comment]
Does it check the box when they claim id? It didn't used to. Once we know when they'll be able to claim again, we can add that information to the page (can create a new issue for it).

**Comment by NetOperatorWibby** [comment]
That screenshot is from one of the status tokens.

**Comment by nikooo777** [comment]
The content is not really in their control though, is it? unless you're referring to status `transferred`

**Comment by tzarebczan** [comment]
@NetOperatorWibby looked at the code, it looks good for the statuses!
