### ISSUE TITLE
Metadata Incorrectly Utilised

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry.com#630]
# META ISSUES

Some of the **metadata** on pages is not utilised correctly.

Using meta tags correctly is vital for **SEO** and **user-friendliness.**

In the below images, you can see how the **Title** and **Description** are **duplicated**.

This looks bad, degrades search positions and can harm **Brand Trust**. It is also is a **missed opportunity** to inform people of what the page is about and increase the [CTR](https://en.wikipedia.org/wiki/Click-through_rate).

The **description tag** is a vital metric search engines use to determine whether or not to display you as a search result and at what position. Read more [here](https://yoast.com/meta-descriptions/).

The **title** and **description** tags have a relationship in **search engine algorithms**, and this relationship always needs to be addressed for each page.

Google understand the error and does a good job at fixing it in search results (see below screenshot). However, it will be harming search positions.

## GOOGLE CRAWL

On top of this, the Google version of the content is different from the actual content. This indicates that page hasn't been **crawled** and **cached** for a long time (several weeks in this case), either due to the **xml sitemap** crawl period set too long or Google not crawling it because of poor **SEO**.

```
This is Google's cache of https://lbry.io/bounty/lbry-club. It is a snapshot of the page as it appeared on 23 Apr 2018 19:05:01 GMT. The current page could have changed in the meantime. Learn more.
```

## TRUST/AUTHORITY 

[Science Of Persuasion](https://youtu.be/cFdCzN7RYbw?t=250)

As a tech company the **trust/authority** of well developed and designed website is vital. It is paramount the website (the companies shop window) is as near perfect as it can be. If it's not, it sends a negative single to potential users or investors.
### LBRY.IO SOURCE
![image](https://user-images.githubusercontent.com/29914179/41215816-65f145c6-6d95-11e8-8bc2-51b3c95317b0.png)
### Google Search Result

Google tries to fix error automatically - Cached copy several weeks out-of-date.
![image](https://user-images.githubusercontent.com/29914179/41216858-5cf5f792-6d99-11e8-8bb2-e8a9751597c7.png)
### Discord Post
![image](https://user-images.githubusercontent.com/29914179/41216399-90664eda-6d97-11e8-83ca-e40ed81ef744.png)
### Facebook Post
![image](https://user-images.githubusercontent.com/29914179/41216213-b8317f80-6d96-11e8-8fa8-c00d4ba28542.png)

**Comment by tzarebczan** [comment]
This feedback is awesome and will help LBRY grow its presence. This should be considered as part of @NetOperatorWibby 's redesign efforts...unless there is an immediate quick fix, then let's do it :)

**Comment by kauffj** [comment]
Change `Response::setMetaDescription` in `view/template/bounty/show.php` to fix this.

If we wait on redesign for this it won't come too fast.

**Comment by Invariant-Change** [comment]
Where is the **metadata** being pulled from? If from the **MarkDown** as seen in the image, it's missing a **description** field, which would need to be added to each page.

[/blob/master/content/faq/bounties.md](https://github.com/lbryio/lbry.io/blob/master/content/faq/bounties.md)

Then could add `<?php Response::setMetaDescription($metadata['description']) ?>` to the templates.

[/blob/master/view/template/bounty/show.php](https://github.com/lbryio/lbry.io/blob/master/view/template/bounty/show.php)

![image](https://user-images.githubusercontent.com/29914179/41423409-9b9aeb2c-703e-11e8-8ecd-5952873d7387.png)

**Comment by kauffj** [comment]
You could do something like
```
<?php Response::setMetaDescription(appropriatesubstring(strip_tags($postHtml))) ?>
```

`$metadata` is also defined and available in the template if you want to build something more custom.

**Comment by Invariant-Change** [comment]
Yeah, that looks cool. Will have a look at this tomorrow (Australian) morning with fresh eyes. All this being upside-down makes me dizzy, haha!

**Comment by alyssaoc** [comment]
@Invariant-Change Were you able to make any progress with this? Thank you

**Comment by kauffj** [comment]
@Invariant-Change this looks like it relates to bounties only, can you re-open if you think there are still outstanding issues here?
