### ISSUE TITLE
Change lbry://wonderfullife caption or change image so that they match in "Art in the Internet Age" essay

### ISSUE THREAD

**Issue by jamesbiller** [lbryio/lbry.com#699]
The caption doesn't match the new image, one needs to be changed so that they match.

<img width="905" alt="screen shot 2018-08-06 at 10 25 54 am" src="https://user-images.githubusercontent.com/38798392/43722482-5a37d0fc-9963-11e8-8dd5-5712fa6fdb34.png">

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
@jamesbiller want to make a new gif with that scenario, or something very similar?

**Comment by kauffj** [comment]
I would keep the example as a well-known video

**Comment by kauffj** [comment]
Fixed, but discovered some other styling issues.
