### ISSUE TITLE
Make categories selector for news page

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry.com#736]
currently LBRY website has categories selector of FAQ Page. like my screenshot in below
![image](https://user-images.githubusercontent.com/26609573/44856340-60456580-ac97-11e8-8e14-ef06b2bf90ea.png)
this shows that the FAQ page is neater. would be nice if the news page have categories selector like FAQ Page. to be neat. and make it easier for visitors to choose which articles or categories they will read.
The News Screenshot on below 
![image](https://user-images.githubusercontent.com/26609573/44856558-f4173180-ac97-11e8-8b7a-2165e9b58433.png)
it is seen that the comparison between FAQ and News Page is more organized FAQ page, Currently news page has two categories its a Community Updates and blog category...  Neat is beautiful. friend. God Bless You

**Comment by tzarebczan** [comment]
Probably one to look at during the lbry.io redesign.

**Comment by NetOperatorWibby** [comment]
We currently don't have categories for blog posts so this is not yet possible.
