### ISSUE TITLE
YouTube Sync first Impression is not clear that it is about Youtube.

### ISSUE THREAD

**Issue by real-rouse** [lbryio/lbry.com#738]
I wrote something in Discord.
See the image:
<img width="737" alt="screen shot 2018-08-31 at 03 43 46" src="https://user-images.githubusercontent.com/30915240/44888261-6ad02100-acd0-11e8-8fea-cdce0a3c544d.png">

**Comment by kauffj** [comment]
@robvsmith please revise this copy if you agree or close this if you do not

**Comment by ykris45** [comment]
i will wait until Mr Rob revise this issues. after it was accepted . i'll fix  this issue

**Comment by robvsmith** [comment]
I will write some new copy for this. Probably not this week, but I do intend to fix this. The whole site, arguably, needs a copy revision - and this would likely be a good place to start.

**Comment by NetOperatorWibby** [comment]
The copy has been updated.
