### ISSUE TITLE
Allow user to enter new email on email management page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#778]
As a user visiting my email management page, I may want to add additional emails (new or existing ones I intend to merge together). This should call our api via `https://api.lbry.io/user_email/new?auth_token=xxxxxxxxxxxxxxx&email=xxxxxxxxxxxxxxx&send_verification_email=true`. If the email is in use, it will 500, and then you call ```https://api.lbry.io/user_email/resend_token```

After the email is confirmed, the page should reflect the new email (monitor for the merge and refresh automatically?)

**Comment by tiger5226** [comment]
It needs to wait until the email is confirmed before refreshing because if that email is tied to another account, the verification will merge the two accounts and only then will the email be tied to this user. 

Unless @kauffj knows a good way to do this with php, we can just post a success message with something along the following lines "Thank you for adding a new email address. We have sent you a verification email, please verify and refresh the page when complete."

**Comment by kauffj** [comment]
@tiger5226 couldn't the API return whether or not the email is attached to an account? Specifically requiring verification to associate is a corner-case.

**Comment by tiger5226** [comment]
Yes, we could return a 202 status code which means 
>The request has been accepted for processing, but the processing has not been completed.

This could be returned if we have to send out a verified to complete the addition of the email to the user account. Then in the UI we catch the 202 and specialize a user friendly message asking them to please verify the email. Would that be acceptable?

**Comment by tzarebczan** [comment]
Realized that this won't be possible without https://github.com/lbryio/lbry.io/issues/559 since the user will need to verify the email, which currently forces them to pass verification to either the desktop or mobile app. 

@alyssaoc should we create a separate email 3.0 epic with these changes, including the app/android side tickets to monitor for web verification instead of expecting it to be passed into the app (app: https://github.com/lbryio/lbry-desktop/issues/1299)

**Comment by tzarebczan** [comment]
This is now possible with lbry.io email verification changes.

**Comment by kauffj** [comment]
I think this should be done on lbry.tv and all email management that is currently happening on lbry.com should move there as well.
