### ISSUE TITLE
Determine where to drive helpdesk contact info from

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry.com#816]
@tzarebczan commented on [Wed Sep 12 2018](https://github.com/lbryio/growth/issues/85)

Possibly add to email footer
Is it on the lbry.io website footer?

---

@jsigwart commented on [Wed Sep 12 2018](https://github.com/lbryio/growth/issues/85#issuecomment-420673297)

Maybe we should think about creating a set of universal info we want in all footers on all LBRY properties? The multiple small requests from Chris45 on are distracting.

**Comment by tzarebczan** [comment]
Closing, there's a new contact page on lbry.com
