### ISSUE TITLE
Handle github API errors gracefully

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry.com#896]
#### Issue Summary

If github API limits are hit or if something doesn't work on their end, our website stops working

#### Steps to Reproduce

1. DDoS github API (gl)
1. break the site cache
3. hammer github API

### Expected result

The API fails but the exception is caught and the website doesn't go down

### Current result

500s everywhere

### Suggested solution

Log the error to slack but continue serving the website

**Comment by NetOperatorWibby** [comment]
This error is still happening, at least locally. Server-side, the site loads slowly. This is the error I see locally:

```
exception 'Exception' with message 'Release array missing assets - possible GitHub auth failure, auth limit, and/or inspect releases array' in ~/Desktop/Projects/LBRY/IO/lib/thirdparty/Github.class.php:41
#0 ~/Desktop/Projects/LBRY/IO/lib/thirdparty/Github.class.php(70): Github::findReleaseAssetForOs(Array(2), 'osx')
#1 ~/Desktop/Projects/LBRY/IO/controller/action/DownloadActions.class.php(121): Github::getRepoAsset('lbry-desktop', 'osx')
#2 ~/Desktop/Projects/LBRY/IO/view/View.class.php(39): DownloadActions::prepareDownloadButtonPartial(Array(1))
#3 ~/Desktop/Projects/LBRY/IO/view/template/nav/_header.php(138): View::render('download/_downloadButton', Array(1))
#4 ~/Desktop/Projects/LBRY/IO/view/View.class.php(65): require('~/Desktop/Projects/LBRY/IO/view/template/nav/_header.php')
#5 ~/Desktop/Projects/LBRY/IO/view/View.class.php(46): View::getTemplateSafely('nav/_header', Array(2))
#6 ~/Desktop/Projects/LBRY/IO/view/template/page/home.php(3): View::render('nav/_header', Array(2))
#7 ~/Desktop/Projects/LBRY/IO/view/View.class.php(65): require('~/Desktop/Projects/LBRY/IO/view/template/page/home.php')
#8 ~/Desktop/Projects/LBRY/IO/view/View.class.php(46): View::getTemplateSafely('page/home', Array(1))
#9 ~/Desktop/Projects/LBRY/IO/controller/Controller.class.php(34): View::render('page/home', Array(1))
#10 ~/Desktop/Projects/LBRY/IO/web/index.php(30): Controller::dispatch('/')
```

**Comment by NetOperatorWibby** [comment]
I shouldn't have to wait 10 minutes before being able to continue working.

Additionally, every time I reload the page (barring this issue), I have to wait almost 3 seconds for the page to load. Maybe an architecture change is necessary at some point to fix that, I'm not sure.

**Comment by NetOperatorWibby** [comment]
Beamer is working on this apparently. https://github.com/lbryio/lbry.io/issues/918

**Comment by NetOperatorWibby** [comment]
@kauffj How can I disable the GitHub calls in development?

**Comment by kauffj** [comment]
@NetOperatorWibby all GitHub calls go through this function:

https://github.com/lbryio/lbry.io/blob/master/lib/thirdparty/Github.class.php#L80

So you could add a switch there to disable or return `null` temporarily.

**Comment by kauffj** [comment]
I was going to fix this but I'm unclear on the issue. Both the homepage and `/get` are loading and accessing the GitHub API for me with no config values declared.

**Comment by NetOperatorWibby** [comment]
@kauffj Reload the page every 2 minutes and you'll see it break.

**Comment by NetOperatorWibby** [comment]
This doesn't seem to be an issue anymore.
