### ISSUE TITLE
Create new LBRY.io OG image

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry.com#898]
@robvsmith commented on [Mon Aug 06 2018](https://github.com/lbryio/growth/issues/39)

Currently its the logo, we should change this.

It should ideally show the app or something else that would be a value add to the viewer. 

One image to be pulled/used by all lbry.io pages.

---

@jsigwart commented on [Wed Aug 15 2018](https://github.com/lbryio/growth/issues/39#issuecomment-413121550)

Brinck suggested the LBRY logo on the background with all of the content on the network. This is good advice for sizing: https://www.h3xed.com/web-and-internet/how-to-use-og-image-meta-tag-facebook-reddit

I can't find that image on this machine - I think it's on my other one at home if Brinck can't find a copy.

---

@robvsmith commented on [Tue Oct 02 2018](https://github.com/lbryio/growth/issues/39#issuecomment-426365713)

I've added Paul (@NetOperatorWibby) to this ticket, since he is working on this with his redesign work.

---

@NetOperatorWibby commented on [Tue Oct 02 2018](https://github.com/lbryio/growth/issues/39#issuecomment-426421807)

For reference, this is the .tech og-image: https://github.com/lbryio/lbry.tech/blob/master/app/dist/media/images/og-image.png.

That article leaves out other important parameters: `og:image:height` and `og:image:width`, which are the pixel sizes of the image.

---

@jsigwart commented on [Tue Oct 02 2018](https://github.com/lbryio/growth/issues/39#issuecomment-426464400)

Is this the correct LBRY arrow book logo?

---

@NetOperatorWibby commented on [Thu Oct 04 2018](https://github.com/lbryio/growth/issues/39#issuecomment-427108642)

I don't know what you mean by "correct". I used what was already in the .tech repo.

---

@NetOperatorWibby commented on [Thu Oct 04 2018](https://github.com/lbryio/growth/issues/39#issuecomment-427108889)

If we want the og:image to be similar in style as .tech, what should the text be?

---

@kauffj commented on [Fri Oct 05 2018](https://github.com/lbryio/growth/issues/39#issuecomment-427464497)

1. Not all pages use the same `og:image`. Any page can explicitly set their own, and many do. Additionally, there is logic to dynamically set the image from images embedded in the content at least for blog posts (and maybe some other page types?). I think this is all good, and should be kept.
2. There is a fallback image when none of the above conditions are met. It's set [here](https://github.com/lbryio/lbry.io/blob/master/view/Response.class.php#L62). I agree this should be changed.
3. The homepage is currently using the fallback image. The homepage should have an image explicitly set in `home.php`. (Search for `Response::addMetaImage` to see how other templates add one).
4. The `og:image` for the homepage should almost certainly feature the browsers in some capacity, as the primary purpose of the homepage is to drive downloads.
5. The overall fallback image I'm more ambivalent about. They don't necessarily need to be the same thing. 

I do not need to review or block shipping this, but please tag me on the PR that changes it.

---

@robvsmith commented on [Wed Nov 28 2018](https://github.com/lbryio/growth/issues/39#issuecomment-442496471)

@NetOperatorWibby - any progress on the OG images?

---

@NetOperatorWibby commented on [Wed Nov 28 2018](https://github.com/lbryio/growth/issues/39#issuecomment-442531616)

@robvsmith Nope, this hasn't been on my radar. Also, no one answered my question above.

**Comment by tzarebczan** [comment]
@Feanor78 / @jsigwart to have the initial lbry.tv OG image functionality, we need this issue resolved first. Then we can work on https://github.com/lbryio/lbry-desktop/issues/2427. 

See lbry.tech OG image for an example of the more modern look for an OG image. Maybe we need to bring Paul in to help.

**Comment by NetOperatorWibby** [comment]
I'm going to create this today

**Comment by kauffj** [comment]
@NetOperatorWibby 

1) 1ede180 did not actually fix change the OG image. You'll need to update this line as well https://github.com/lbryio/lbry.com/blob/master/view/Response.class.php#L64 (no need to PR)
2) Would it make more sense to show a screenshot of the app than of the website?

**Comment by NetOperatorWibby** [comment]
@kauffj Actually yes, it would make more sense to show the app.
