### ISSUE TITLE
Tag awareness of email management page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#906]
Credit to @nikooo777 for the idea and @kauffj for exposing the UX issue. 

Currently, when a user visits the email management page they see a global off option as well as toggles for each type of subscription which may be confusing, especially when coming from targeted emails (their first inclination may be to unsubscribe all if they can't tell which toggle to click). 

For those targeted email, we should allow the email management page to accept the tag as a parameter and guide the user directly to the tag they may want to turn off. One implementation of this would just be to show the tag (if passed), and then an option underneath to see the other tags/global on/off.

**Comment by tiger5226** [comment]
I think it would be best to just show the switch for the specific tag only. We should probably just call the api when they land on the page to unsubscribe them to make it easier and the popup confirms it with them. Then at the bottom in small print we say, `click here to manage all email settings`. This would then redirect them to the main email management page.

**Comment by kauffj** [comment]
@tiger5226 are the tags currently being injected into the unsubscribe URLs?

**Comment by tzarebczan** [comment]
@kauffj yep, this is a recent subscription email: - https://lbry.com/list/edit/xxxxxxxxxxxxxxxxxx?tag=subscription

**Comment by tiger5226** [comment]
The only one that it is on is the subscription one. I am not aware of others that are passing the tag yet.

**Comment by nikooo777** [comment]
can we close this issue or should we further work on it?

**Comment by tzarebczan** [comment]
Probably can close..think the descriptions are good enough.
