### ISSUE TITLE
Improve email / LBRY account flow for YouTube Sync

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#923]
#### Issue Summary

Currently, if a YouTuber goes through the sync process and tries to update their email to one that already exists in our database, they get an error and are told to contact help@lbry.io. With the new email verification changes in place, we should be able to support a scenario where they can merge their accounts automatically using something similar to the call specified in https://github.com/lbryio/lbry.io/issues/778.  

We also don't verify their email, neither the original yt sync one or the newly entered email. Instead, we should have them verify their initial YouTube account email, and show them a message that sync is pending verification (this will make sure they change the google pages email). We should also make them verify their email when they change it from the default youtube email (google pages one, or other), and show same pending verification message. 

Currently we show "Go Back To The App" after email verification - we may need to remove this, or only show if it's an app email verification request, and not request from lbry.io (yt sync, or email management page).

**Comment by robvsmith** [comment]
I've been digging through our metabase data as we try to focus on creator partnerships, and have found some potential high value targets who are falling off along this way. Who would need to do this work @kauffj ?

The ideal follow up for a Pending Creator would include a link to, with one click, claim their channel and become confirmed. Maybe that's impossible, but I think we should work back from ideal and have this function as close to ideal as possible for outreach.

We have multiple 1m+ subs who are in this "pending" vortex, and none of them are technical channels - rappers, fitness, unboxing, etc. I would not expect these people to be willing to follow a lot of steps along the way.

**Comment by kauffj** [comment]
I think @tzarebczan understands the state of this better than I do.

Tom and/or @tiger5226, would it make sense to just generically support merging accounts (assuming you can authenticate to both)? Would the fix for the YouTube side of this fall out of that solution?

**Comment by tzarebczan** [comment]
@kauffj the support for merging accounts is already there, given an existing auth token + new email. Once the email is confirmed, the accounts are merged. For YouTube sync, this process is very similar but would be done directly on the /youtube page. I'd like other merging to happen directly on the maintenance page via https://github.com/lbryio/lbry.io/issues/778 (a youtuber could also do it this way, assuming they can auth to the edit page, which isn't possible for google plus emails).

**Comment by tzarebczan** [comment]
From Niko:
```- Users that sign up and do not have an email (aka have a default g+ email) will be required to provide a valid email
- Users that sign up and have a valid email that doesn't already exist on lbry will automatically have it marked as verified
- Users that sign up with a valid email that already exists in the system will be asked to confirm it before merging the accounts (to avoid stealing accounts)
- Users that sign up without an email and then provide an email that doesn't exist in the system will automatically have it verified
- Users that change their email but that already had at least one email in their account will have to verify the new email (to avoid abuse)
- Users that change/provide their email and for which the new email is already in the system will have to verify the email

On top of that, the immediateSync flag is again functional, a small bit of work is still necessary to feed the ytsync servers, but at least we'll have them converted.```

**Comment by tzarebczan** [comment]
From Slack discussion on next steps:
```Once you get to the status page, you'd have to check the Status field. If it's equal to `pendingemail`, this means their account has a googleplus email, and we want them to verify it before they agree to sync. Otherwise, they don't have to do anything on the status page (they should be agreed, and with the right channel since they chose it on the /youtube page).

The next steps depend on if they already have a LBRY email or not - you get this information from the `HasVerifiedEmail` flag. If they don't have a lbry account, it gets verified right away (set to true) and they can sync (check the box for them automatically?). If they do have an email, they need to verify it first (they'll get a verification, and we need to re-call the status api until HasVerifiedEmail is set to true).  The "pending email" is not saved anywhere before it's verified...Niko said he could add this if needed.```

**Comment by NetOperatorWibby** [comment]
While going through the sync process I get:

```
The following error occurred: type: cannot be blank. For support please send an email to hello@lbry.com.
```

This error does not exist on prod so that means Google’s email checker is not authorizing `localhost:8000` to access it.

**Comment by tzarebczan** [comment]
Currently blocked by https://github.com/lbryio/internal-apis/issues/849 

@nikooo777 can you confirm this is only for the case where the email already exists in LBRY? If it's a new email, the API should already have it right?

**Comment by nikooo777** [comment]
The above is correct. I went down the rabbit hole and I found the blocker.
