### ISSUE TITLE
Change/add success threshold for YouTube conversion

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#958]
Update https://github.com/lbryio/lbry.io/blob/master/view/template/acquisition/youtube_status.php so that the FB and GA success event only fires if the sync was above a certain quality threshold.

**Comment by NetOperatorWibby** [comment]
@kauffj What's the quality threshold?

**Comment by kauffj** [comment]
@finer9 @robvsmith can you guys agree on what subscriber and/or video view count you want this to trigger on and comment on the ticket with the answer?

**Comment by kauffj** [comment]
@finer9 still need threshold values for this

**Comment by kauffj** [comment]
@finer9 I'm closing this, please re-open with values if you want this done.
