### ISSUE TITLE
Blog comments

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#974]
Is there a free/open-source drop-in plugin that could allow commenting on news posts?

**Comment by jsigwart** [comment]
Company news is not a great place for comments. I feel news should be stand
alone releases, then discussion should happen on a discussion forum.

**Comment by iamflorencejay** [comment]
Try this @kauffj 
https://posativ.org/isso/

**Comment by kauffj** [comment]
thanks for sharing, but the blog has essentially been deprecated in favor of the official @lbry channel
