### ISSUE TITLE
Redo /youtube and /youtube/status

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.com#975]
- /youtube needs the second callout/sync action restored
- The status page needs to generally be reworked and be clearer about next steps, particularly when the email is missing

**Comment by tzarebczan** [comment]
Related? https://github.com/lbryio/lbry.io/issues/933

**Comment by nikooo777** [comment]
it sort of is, but thanks for bringing that issue up, I hadn't seen it. So this outlines that the button wasn't working when we removed it last week.

We intend to bring it back. @NetOperatorWibby needs to take the following parameters in mind once a user lands on /status
- If `has_verified_email` is set to false then the user needs to be alerted that they need to verify the email before they can continue. There needs to no room for misinterpretation or doubts
- if `email` is empty then they need to provide an email and verify it. same as above

I will be adding an additional ytsync status called `pendingemail` so those that sign up with the `sync now` button will automatically be moved into `queued` as soon as they verify their email.

The current page has a rather bad UX and I'd argue the UI is also bad as users need to scroll down to figure out what they have to do (and they have to sort of guess), the top headers can't be clicked (Josh and others were confused when clicking the box here https://scrn.storni.info/2019-03-07_17-12-28-604995302.png wouldn't do anything), i'd either rework/resize it or get rid of it.

It would be ideal to rethink the UI/UX to better convert incoming youtubers.

The information at your disposal are (see the json field name):
```
		Email              string      `json:"email"`
		LBRYChannelName    null.String `json:"lbry_channel_name"`
		Status             null.String `json:"status"`
		ExpectedReward     int         `json:"expected_reward"`
		RedeemedReward     int         `json:"redeemed_reward"`
		Subscribers        null.Uint   `json:"subscribers"`
		Videos             null.Uint   `json:"videos"`
		Editable           bool        `json:"editable"`
		YoutubeChannelName null.String `json:"youtube_channel_name"`
		Transferred        bool        `json:"transferred"`
		Fee                *claimFee   `json:"fee"`
		HasVerifiedEmail   bool        `json:"has_verified_email"`
```

**Comment by tzarebczan** [comment]
Some suggestions:
- Show spee.ch / open.lbry.com / beta.lbry.tv urls for synced channels
- Hover over with explanations of each status
- Show allowed characters in channel name (this may change with the recent HF to support more characters)
- Show when the reward has been redeemed, and date of next available reward (if we are going with yearly, 1 year from sync or 1 year from redemption?)
- Allow users to set a fee per video
- Mention pay per view program?
- Show referral URL so they can share it immediately? 
- Make next steps about downloading app / claiming reward / claiming content (soonish) clearer
