### ISSUE TITLE
Top nav sometimes hides if you try to mouse toward Get LBRY

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry.com#983]
![nav](https://user-images.githubusercontent.com/362784/54543559-3ffba080-4974-11e9-9eea-71db18418715.gif)

**Comment by kauffj** [comment]
@NetOperatorWibby I saw this on @lyoshenka's computer today. I think the triangles must not be wide enough or fat enough at the top.

**Comment by NetOperatorWibby** [comment]
Good grief. All right

**Comment by NetOperatorWibby** [comment]
@lyoshenka Do you still have this issue?

**Comment by lyoshenka** [comment]
Less so, but still happens. Its the worst when going from Delevopers to
LBRY.tech.

**Comment by NetOperatorWibby** [comment]
I think I just found a possible way forward, I'll push it today.

**Comment by NetOperatorWibby** [comment]
Closed via https://github.com/lbryio/lbry.com/commit/f2b9d57f2e2249dfd73ef89678a8166f8be44e26

**Comment by kauffj** [comment]
@lyoshenka how about now?

**Comment by NetOperatorWibby** [comment]
@kauffj I asked him on Slack
