### ISSUE TITLE
Can’t enable disable items on /edit page when clicking directly on checkbox

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#985]
Can’t enable disable items on /edit page when clicking directly on checkbox - you need to click on the next to it

**Comment by jsigwart** [comment]
Beamer posted 4 lines of code last night to fix the CSS in Slack... would be really nice if this were fixed soon.

**Comment by NetOperatorWibby** [comment]
Was I tagged in that message?
