### ISSUE TITLE
Hyperlinks only work when when you hover over text on menu

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#989]
If you mouse over a menu, the text highlights which seems like you can click it, but can only do so when you directly click the text.  A few users have expressed confusion around this. 

![image](https://user-images.githubusercontent.com/8120721/54644782-a1089e80-4a70-11e9-9a14-67fbabb64476.png)

![image](https://user-images.githubusercontent.com/8120721/54644809-ae258d80-4a70-11e9-982b-ef5eb680c8b8.png)

**Comment by tzarebczan** [comment]
Something similar on the nav menu, but this may be by design 
![image](https://user-images.githubusercontent.com/8120721/54646781-a36df700-4a76-11e9-9478-87026cf4bf3d.png)

**Comment by Invariant-Change** [comment]
The link need to be assigned to the `<drawer-child>` not the string that it currently is `<a href="/team">.`
![image](https://user-images.githubusercontent.com/29914179/54655556-1d9d8a80-4b0e-11e9-849b-25f52a5e768f.png)

**Comment by NetOperatorWibby** [comment]
No, that's not going to work @Invariant-Change.

@tzarebczan In order to have "more forgiving" mouse paths, I had to add an additional element that covers un-hovered top-level menu items.
