### ISSUE TITLE
Display Issues with Landing pages

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry.com#990]
#### Issue Summary

Landing pages have CSS and display issues:

https://lbry.com/CU
https://lbry.com/pi

<img width="1305" alt="Screen Shot 2019-03-19 at 3 45 23 PM" src="https://user-images.githubusercontent.com/1363664/54647259-0bb0de80-4a5f-11e9-8d58-b4a582aa7188.png">
<img width="1401" alt="Screen Shot 2019-03-19 at 2 49 51 PM" src="https://user-images.githubusercontent.com/1363664/54647260-0bb0de80-4a5f-11e9-952d-f4e4a94695be.png">
<img width="401" alt="Screen Shot 2019-03-19 at 2 29 58 PM" src="https://user-images.githubusercontent.com/1363664/54647261-0bb0de80-4a5f-11e9-8a3e-6a6bd69a2404.png">

**Comment by NetOperatorWibby** [comment]
The code to fix this in currently in the repo, the auto-deploy function on the server has an issue and thus the changes are not reflected.

**Comment by NetOperatorWibby** [comment]
Server has been manually updated.
