### ISSUE TITLE
Menu Links Don't Work on Touchscreens

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry.com#992]
#### Issue Summary

Top level menu links don't work on touch screens.
When you press them, nothing happens.

![image](https://user-images.githubusercontent.com/29914179/54656224-8980f280-4b10-11e9-96b1-8ad0bffa39a0.png)

**Comment by tzarebczan** [comment]
Seem to work here on mobile + desktop mode in chrome.

**Comment by Invariant-Change** [comment]
Mobile is fine as it turns in to the mobile menu. I can only test on the iPad for touch, so can't comment on other touch devices!

**Comment by NetOperatorWibby** [comment]
I didn't think about tablets, just phone and desktops. Thanks for catching this
