### ISSUE TITLE
Fix size of GIF on android page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#994]
Pretty sure this used to be larger...
![Screenshot_20190320-104537](https://user-images.githubusercontent.com/8120721/54693706-70227b00-4afd-11e9-86dc-e33c1980ed4d.jpg)

**Comment by NetOperatorWibby** [comment]
How large does it need to be?

**Comment by tzarebczan** [comment]
Something that fills in more of the page? Looks like it's being shrunk right now.
