### ISSUE TITLE
HTML Embed Tweet and other was dissapears 

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry.com#997]
## FAQ
![image](https://user-images.githubusercontent.com/26609573/54702783-1f953700-4b6a-11e9-8757-e5a2ef3f0da4.png)
## NEWS
![image](https://user-images.githubusercontent.com/26609573/54703028-a21df680-4b6a-11e9-90e6-f815e9916f38.png)

#### Steps to Reproduce

1. go https://lbry.com
2. move to FAQ section
3. click How do I use the Twitter tipbot? and https://lbry.com/news/hacktoberfest
and see as my screenshot on above

**Comment by NetOperatorWibby** [comment]
This was done on purpose to get JS out of Markdown files and to unify blockquote styling.
