### ISSUE TITLE
Mobile UX issues

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry.com#998]
### Issue Summary

Google reporting mobiles errors including:
- touch elements too close
- content wider than the screen

Here is the link Google sent: https://support.google.com/webmasters/answer/9063469

#### Screenshot showing horizontal scrollbar
<img width="401" alt="Screen Shot 2019-03-20 at 9 59 30 PM" src="https://user-images.githubusercontent.com/1363664/54734504-3c773d80-4b5d-11e9-8944-f025a7ca01c4.png">

#### More cut off content
<img width="400" alt="Screen Shot 2019-03-20 at 10 13 56 PM" src="https://user-images.githubusercontent.com/1363664/54734561-a09a0180-4b5d-11e9-9936-cf6593f87b9a.png">

#### Footer menus cut off on my iPhone
![IMG_0491](https://user-images.githubusercontent.com/1363664/54734768-33876b80-4b5f-11e9-8029-6226ee3cc792.PNG)

#### iOS menus don't work
The dropdown menus do not dropdown on my iPhone when I touch them:
![IMG_0492](https://user-images.githubusercontent.com/1363664/54734745-08048100-4b5f-11e9-81da-51f1d1f40765.PNG)

**Comment by NetOperatorWibby** [comment]
Ahhh, I didn't realize my "fix" yesterday removed the links from the mobile menu. Yikes

**Comment by NetOperatorWibby** [comment]
Code snippets are typically horizontally scrolled on mobile devices.
