### ISSUE TITLE
Insecure links in lbry emails

### ISSUE THREAD

**Issue by simon816** [lbryio/lbry.com#999]
Not sure if this is the best place to raise the issue but don't know where else.

Hyperlinks in emails from LBRY are insecure and there is no HTTPS available.
The links are to the URL:
`http://email.mail.lbry.io`
and more recently:
`http://email.mail.lbry.com/`

Trying to visit `https://` at these domains doesn't connect.

Also, the urls are long meaningless base64 strings - I have no idea where I'll be redirected before I click on it, and past experience tells me that when the base64 string inevitably is purged from lbry's redirector, I won't be redirected to the proper url.

**Comment by tzarebczan** [comment]
HEy @simon816 , thanks for submitting the issue, we'll investigate! Can we send you some [LBC as appreciation](https://lbry.com/faq/appreciation) for the report?

**Comment by tzarebczan** [comment]
@simon816 looks like it's related to how our mail servers tracks clicks for analytics. It's just a redirect to one of our HTTPS URLs. We'll check out https://help.mailgun.com/hc/en-us/articles/360011566033-How-to-enable-HTTPS-tracking-links and see if we want to switch.

**Comment by binaryflesh** [comment]
A quick look at lbry.com's TXT record indicates there is not [SPF](https://en.wikipedia.org/wiki/Sender_Policy_Framework) or [DMARC](https://dmarc.org/overview/) setup:
```sh
# dig +short @8.8.8.8 TXT lbry.com AA
"google-site-verification=C0pGkuE_q821khQGjcjArAFB5_18wdh5OkIxo1x1qhM"
"ca3-13e31e87a6744416a362377d6768d16b"
"google-site-verification=x3vr8__SBMXV6GSfT6yQBIksWhyb4oNNVuWi5YbtzvE"
```
to actually be in fully prove an email came from your endpoint, you usually add the SPF or DMARC Record along with the DKIM key of your MTA(Mail transfer agent). This tells the world who can send email on your behalf and a public key to verify. the above verifies there is no way for Bob know what how can send as `lbry.com`. Although a security talk, this is still a [good deep dive](https://www.youtube.com/watch?v=30TLngOVwqQ) to prevent spoofing and insure the integrity of your domain's email at any scale.

**Comment by nikooo777** [comment]
Hey @binaryflesh while we don't yet have DMARC set up we do have TXT/SPF records in place: https://mxtoolbox.com/SuperTool.aspx?action=txt%3amail.lbry.com&run=toolpage

we send emails from mail.lbry.com, not lbry.com
I will however investigate further as we just changed our email domain from .io to .com so something could have slipped through

**Comment by alyssaoc** [comment]
@robvsmith is this at all related to the changes you just made?

**Comment by robvsmith** [comment]
I do not _think_ this has to do with me - though I'm always open to being wrong! 

I've been changing links within the email itself that were broken, but nothing to do with where they are sent from.

**Comment by tzarebczan** [comment]
@robvsmith nope, it's a mailgun thing :)

**Comment by tzarebczan** [comment]
Going to close this - we're tracking it internally with a low priority since getting this setup would require a more expensive cloudflare account, unless mailgun makes it easier to do. 

The DMARC issue has been fixed: https://us.dmarcian.com/dmarc-xml/details/6L84fPSpY5ltAnJq/
